# Generated by Django 5.2.1 on 2025-06-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_loginattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
    ]
