# Generated by Django 5.2.1 on 2025-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cartitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
