# Generated by Django 5.2.1 on 2025-06-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productpage_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.FloatField(),
        ),
    ]
