#version :'3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - development.env
