version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - development.env
    depends_on:
      - redis
